In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [2]:
pd.options.mode.chained_assignment = None  # default='warn'

In [5]:
# Download training data
df_training = pd.read_csv("https://raw.githubusercontent.com/SwapnilRaghuvanshi/ADMN-5015/main/Training%20data.csv")
df_training

ssc_p  hsc_p  degree_p  etest_p  status
0     65.0   75.0      69.0    72.00       1
1     63.0   66.2      65.6    60.00       1
2     55.0   67.0      64.0    60.00       0
3     63.0   66.0      64.0    68.00       0
4     60.0   67.0      70.0    50.48       1
..     ...    ...       ...      ...     ...
195   80.6   82.0      77.6    91.00       1
196   58.0   60.0      72.0    74.00       1
197   67.0   67.0      73.0    59.00       1
198   74.0   66.0      58.0    70.00       1
199   62.0   58.0      53.0    89.00       0

[200 rows x 5 columns]

In [6]:
# Make sure data types are correct (no objects)

df_training.dtypes

ssc_p       float64
hsc_p       float64
degree_p    float64
etest_p     float64
status        int64
dtype: object

In [8]:
# Pop label

target = df_training.pop('status')

In [10]:
# Define features

numeric_feature_names = ['ssc_p', 'hsc_p', 'degree_p', 'etest_p']
numeric_features = df_training[numeric_feature_names]
numeric_features.head()

ssc_p  hsc_p  degree_p  etest_p
0   65.0   75.0      69.0    72.00
1   63.0   66.2      65.6    60.00
2   55.0   67.0      64.0    60.00
3   63.0   66.0      64.0    68.00
4   60.0   67.0      70.0    50.48

In [11]:
# Convert data to Tensorflow tensor

numeric_features = tf.convert_to_tensor(numeric_features)
numeric_features

<tf.Tensor: shape=(200, 4), dtype=float64, numpy=
array([[65.  , 75.  , 69.  , 72.  ],
       [63.  , 66.2 , 65.6 , 60.  ],
       [55.  , 67.  , 64.  , 60.  ],
       [63.  , 66.  , 64.  , 68.  ],
       [60.  , 67.  , 70.  , 50.48],
       [62.  , 65.  , 66.  , 50.  ],
       [79.  , 76.  , 85.  , 95.  ],
       [69.8 , 60.8 , 72.23, 55.53],
       [77.4 , 60.  , 64.74, 92.  ],
       [76.5 , 97.7 , 78.86, 97.4 ],
       [52.58, 54.6 , 50.2 , 76.  ],
       [71.  , 79.  , 66.  , 94.  ],
       [63.  , 67.  , 66.  , 68.  ],
       [76.76, 76.5 , 67.5 , 73.35],
       [62.  , 67.  , 58.  , 77.  ],
       [64.  , 73.5 , 73.  , 52.  ],
       [67.  , 53.  , 65.  , 64.  ],
       [61.  , 81.  , 66.4 , 50.89],
       [87.  , 65.  , 81.  , 88.  ],
       [62.  , 51.  , 52.  , 68.44],
       [69.  , 78.  , 72.  , 71.  ],
       [51.  , 44.  , 57.  , 64.  ],
       [79.  , 76.  , 65.6 , 58.  ],
       [73.  , 58.  , 66.  , 53.7 ],
       [81.  , 68.  , 64.  , 93.  ],
       [78.  , 77.  , 80.

In [12]:
# Normalize data

normalizer = tf.keras.layers.Normalization(axis=-1)
normalizer.adapt(numeric_features)

In [13]:
# Define model

def get_basic_model():
  model = tf.keras.Sequential([
    normalizer,
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(3) # Possible labels 0, 1 or 2
  ])

  model.compile(optimizer='adam',
                loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
                # loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
                metrics=['accuracy'])
  return model

In [15]:
# Train model

BATCH_SIZE = 128

model = get_basic_model()
model.fit(numeric_features, target, epochs=700, batch_size=BATCH_SIZE)

Epoch 1/700
2/2 [==============================] - 0s 8ms/step - loss: 1.3864 - accuracy: 0.0950
Epoch 2/700
2/2 [==============================] - 0s 6ms/step - loss: 1.3619 - accuracy: 0.1200
Epoch 3/700
2/2 [==============================] - 0s 6ms/step - loss: 1.3392 - accuracy: 0.1450
Epoch 4/700
2/2 [==============================] - 0s 7ms/step - loss: 1.3169 - accuracy: 0.1450
Epoch 5/700
2/2 [==============================] - 0s 6ms/step - loss: 1.2947 - accuracy: 0.1700
Epoch 6/700
2/2 [==============================] - 0s 6ms/step - loss: 1.2736 - accuracy: 0.1800
Epoch 7/700
2/2 [==============================] - 0s 5ms/step - loss: 1.2534 - accuracy: 0.1900
Epoch 8/700
2/2 [==============================] - 0s 6ms/step - loss: 1.2337 - accuracy: 0.1900
Epoch 9/700
2/2 [==============================] - 0s 7ms/step - loss: 1.2142 - accuracy: 0.1900
Epoch 10/700
2/2 [==============================] - 0s 6ms/step - loss: 1.1953 - accuracy: 0.1950
Epoch 11/700
2/2 [===========

In [16]:
# Download test data

df_test = pd.read_csv("https://raw.githubusercontent.com/SwapnilRaghuvanshi/ADMN-5015/main/Testing%20data.csv")
df_test.head()

ssc_p  hsc_p  degree_p  etest_p  status
0  67.00  91.00     58.00     55.0       1
1  79.33  78.33     77.48     86.5       1
2  65.00  68.00     64.00     75.0       1
3  56.00  52.00     52.00     66.0       0
4  85.80  73.60     73.30     96.8       1

In [17]:
# Pop label

test_target = df_test.pop('status')

In [18]:
# Define test features

test_numeric_feature_names = ['ssc_p', 'hsc_p', 'degree_p', 'etest_p']
test_numeric_features = df_test[test_numeric_feature_names]
test_numeric_features.head()

ssc_p  hsc_p  degree_p  etest_p
0  67.00  91.00     58.00     55.0
1  79.33  78.33     77.48     86.5
2  65.00  68.00     64.00     75.0
3  56.00  52.00     52.00     66.0
4  85.80  73.60     73.30     96.8

In [19]:
# Convert test data to Tensorflow tensor

test_numeric_features = tf.convert_to_tensor(test_numeric_features)
test_numeric_features

<tf.Tensor: shape=(15, 4), dtype=float64, numpy=
array([[67.  , 91.  , 58.  , 55.  ],
       [79.33, 78.33, 77.48, 86.5 ],
       [65.  , 68.  , 64.  , 75.  ],
       [56.  , 52.  , 52.  , 66.  ],
       [85.8 , 73.6 , 73.3 , 96.8 ],
       [55.  , 49.8 , 67.25, 55.  ],
       [46.  , 49.2 , 79.  , 74.28],
       [82.  , 64.  , 66.  , 67.  ],
       [73.  , 79.  , 72.  , 91.34],
       [58.  , 70.  , 61.  , 54.  ],
       [58.  , 61.  , 60.  , 62.  ],
       [69.6 , 68.4 , 78.3 , 60.  ],
       [47.  , 55.  , 65.  , 62.  ],
       [77.  , 87.  , 59.  , 68.  ],
       [62.  , 47.  , 50.  , 76.  ]])>

In [20]:
# Normalize data

normalizer = tf.keras.layers.Normalization(axis=-1)
normalizer.adapt(test_numeric_features)

In [21]:
# Evaluate test data based on training data

score = model.evaluate(test_numeric_features, test_target, verbose=1)
print(f'Test loss: {score[0]} / Test accuracy: {score[1]}')

1/1 [==============================] - 0s 163ms/step - loss: 0.4282 - accuracy: 0.8667
Test loss: 0.428245484828949 / Test accuracy: 0.8666666746139526


In [ ]:
# Save model (optional)

# model.save('iris_model')

In [22]:
# Download cases to be predicted

df_predict = pd.read_csv("https://raw.githubusercontent.com/SwapnilRaghuvanshi/ADMN-5015/main/Campus%20Recruitment.csv")
df_predict

ssc_p  hsc_p  degree_p  etest_p
0  67.00  91.00     58.00     55.0
1  79.33  78.33     77.48     86.5
2  65.00  68.00     64.00     75.0

In [23]:
# Make sure data types are correct (no objects)

df_predict.dtypes

ssc_p       float64
hsc_p       float64
degree_p    float64
etest_p     float64
dtype: object

In [24]:
# Convert data to Tensorflow tensor

predict_numeric_features = tf.convert_to_tensor(df_predict)
predict_numeric_features

<tf.Tensor: shape=(3, 4), dtype=float64, numpy=
array([[67.  , 91.  , 58.  , 55.  ],
       [79.33, 78.33, 77.48, 86.5 ],
       [65.  , 68.  , 64.  , 75.  ]])>

In [25]:
# Normalize

normalizer = tf.keras.layers.Normalization(axis=-1)
normalizer.adapt(predict_numeric_features)

In [26]:
# Predict labels

class_names = ['Placed', 'Not Placed']

predictions = model(predict_numeric_features, training=False)

# Create new columns in dataframe
df_predict['label'] = None
df_predict['certainty'] = None

for i, logits in enumerate(predictions):
  class_idx = tf.argmax(logits).numpy()
  p = tf.nn.softmax(logits)[class_idx]
  name = class_names[class_idx]
  print("Example {} prediction: {} ({:4.1f}%)".format(i, name, 100*p))

  # Save predictions to dataframe
  df_predict["label"].iloc[i] = name
  df_predict['certainty'].iloc[i] = format(p)


Example 0 prediction: Not Placed (85.7%)
Example 1 prediction: Not Placed (99.9%)
Example 2 prediction: Not Placed (81.0%)


In [27]:
df_predict


ssc_p  hsc_p  degree_p  etest_p       label           certainty
0  67.00  91.00     58.00     55.0  Not Placed  0.8572776913642883
1  79.33  78.33     77.48     86.5  Not Placed  0.9993261098861694
2  65.00  68.00     64.00     75.0  Not Placed   0.809586763381958